from enum import Enum


class EventType(Enum):
    """Enum containing the various types of events that can occur."""
    CLIENT_READY = "CLIENT_READY"
    CLIENT_RESUMED = "CLIENT_RESUMED"

    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    SERVER_MESSAGE_RECEIVED = "SERVER_MESSAGE_RECEIVED"
    PRIVATE_MESSAGE_RECEIVED = "PRIVATE_MESSAGE_RECEIVED"
    COMMAND_RECEIVED = "COMMAND_RECEIVED"

    MESSAGE_DELETED = "MESSAGE_DELETED"
    MESSAGE_EDITED = "MESSAGE_EDITED"

    CHANNEL_DELETED = "CHANNEL_DELETED"
    CHANNEL_CREATED = "CHANNEL_CREATED"
    CHANNEL_UPDATED = "CHANNEL_UPDATED"

    MEMBER_JOINED = "MEMBER_JOINED"
    MEMBER_REMOVED = "MEMBER_REMOVED"
    MEMBER_UPDATED = "MEMBER_UPDATED"
    MEMBER_BANNED = "MEMBER_BANNED"
    MEMBER_UNBANNED = "MEMBER_UNBANNED"
    MEMBER_TYPING = "MEMBER_TYPING"

    SERVER_JOINED = "SERVER_JOINED"
    SERVER_REMOVED = "SERVER_REMOVED"
    SERVER_UPDATED = "SERVER_UPDATED"

    ROLE_CREATED = "ROLE_CREATED"
    ROLE_DELETED = "ROLE_DELETED"
    ROLE_UPDATED = "ROLE_UPDATED"

    SERVER_AVAILABLE = "SERVER_AVAILABLE"
    SERVER_UNAVAILABLE = "SERVER_UNAVAILABLE"

    VOICE_STATE_UPDATED = "VOICE_STATE_UPDATED"

    REACTION_ADDED = "REACTION_ADDED"
    REACTION_REMOVED = "REACTION_REMOVED"
    REACTIONS_CLEARED = "REACTIONS_CLEARED"

    MEMBER_JOINED_GROUP = "MEMBER_JOINED_GROUP"
    MEMBER_REMOVED_FROM_GROUP = "MEMBER_REMOVED_FROM_GROUP"

    SERVER_EMOJIS_UPDATED = "SERVER_EMOJIS_UPDATED"


class RedisStorageScope(Enum):
    """Enum containing the possible Redis storage scopes."""
    GLOBAL = "GLOBAL"
    PLUGIN = "PLUGIN"
    SERVER = "SERVER"
    CHANNEL = "CHANNEL"
    USER = "USER"
